//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUserStore
    {
        public int id { get; set; }
        public string admin_user_id { get; set; }
        public int store_id { get; set; }
        public System.DateTime store_from { get; set; }
        public Nullable<System.DateTime> store_to { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public string updated_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
