//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWorker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebWorkSystemEntities : DbContext
    {
        public WebWorkSystemEntities()
            : base("name=WebWorkSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUsers> AdminUsers { get; set; }
        public virtual DbSet<AdminUserStore> AdminUserStore { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserStore> UserStore { get; set; }
    }
}
