//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string familyname { get; set; }
        public string firstname { get; set; }
        public string familyname_kana { get; set; }
        public string firstname_kana { get; set; }
        public System.DateTime birthday { get; set; }
        public int sex_type { get; set; }
        public System.DateTime joined_date { get; set; }
        public Nullable<System.DateTime> leaved_date { get; set; }
        public string password { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public string updated_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
